# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.40
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

package parisrv;
use base qw(Exporter);
use base qw(DynaLoader);
package parisrvc;
bootstrap parisrv;
package parisrv;
@EXPORT = qw();

# ---------- BASE METHODS -------------

package parisrv;

sub TIEHASH {
    my ($classname,$obj) = @_;
    return bless $obj, $classname;
}

sub CLEAR { }

sub FIRSTKEY { }

sub NEXTKEY { }

sub FETCH {
    my ($self,$field) = @_;
    my $member_func = "swig_${field}_get";
    $self->$member_func();
}

sub STORE {
    my ($self,$field,$newval) = @_;
    my $member_func = "swig_${field}_set";
    $self->$member_func($newval);
}

sub this {
    my $ptr = shift;
    return tied(%$ptr);
}


# ------- FUNCTION WRAPPERS --------

package parisrv;

*parisrv_init = *parisrvc::parisrv_init;
*parisrv_eval = *parisrvc::parisrv_eval;
*parisrv_close = *parisrvc::parisrv_close;
*parisrv_nb_hist = *parisrvc::parisrv_nb_hist;

# ------- VARIABLE STUBS --------

package parisrv;

1;
